export { default as About } from "./About"
export { default as AuthLogin } from "./Auth/Login"
export { default as AuthRegister } from "./Auth/Register"
export { default as Cart } from "./Cart"
export { default as Home } from "./Home"