name: Deploy React Frontend to GitHub Pages

permissions:
  contents: write  # 確保 GITHUB_TOKEN 有權限推送

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Clean and install dependencies
        working-directory: silkroad-frontend-react
        run: |
          rm -rf node_modules package-lock.json
          npm ci

      - name: Build
        working-directory: silkroad-frontend-react
        run: npm run build

      - name: List dist folder
        run: ls -la silkroad-frontend-react/dist  # 確認 build 成功

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: silkroad-frontend-react/dist
